name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run tests
      run: |
        # Assuming you have pytest or another test framework set up
        pytest tests/

    - name: Build macOS executable
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --windowed src/gui/file_transfer_gui.py
        pyinstaller --onefile src/server/server.py

    - name: Build Windows executable
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile src/gui/file_transfer_gui.py
        pyinstaller --onefile src/server/server.py

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: builds
        path: |
          dist/file_transfer_gui
          dist/server
