name: Build with PyInstaller

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3'  

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Clean previous build artifacts
      run: |
        rm -rf file_transfer_project/gui/dist

    - name: Build with PyInstaller
      run: |
        cd file_transfer_project/gui
        pyinstaller --onefile --windowed file_transfer_gui.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: file_transfer_project/gui/dist
